language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  # apt:
  #   packages:
  #     - oracle-java8-installer
  #     - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    # Copy/paste from XMLDBEditor should not be linted.
    - IGNORE_PATHS=db/upgrade.php

  matrix:
    - MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli

matrix:
  exclude:

    # Exclude builds not compatible with 5.6.
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli

    # Exclude builds not compatible with 7.2.
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  # - moodle-plugin-ci behat

  # The following plugins are disabled:
  # - moodle-plugin-ci phpmd
  # - moodle-plugin-ci phpcpd
